// 스터디룸 관련 더미데이터

import type { ApiResponse, RoomDetail } from "@/@types/roomss";

const now = new Date("2025-10-01T06:46:09.122Z");

export const MOCK_ROOMS_20: ApiResponse<RoomDetail>[] = [
  // 기존 1~11
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1001,
      title: "고양이 알고리즘 스터디",
      description: "배열, 스택, 큐 연습하기",
      maxParticipants: 6,
      currentParticipants: 3,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: false,
      createdBy: "uha",
      createdAt: now.toISOString(),
      members: [
        { userId: 1, nickname: "은주", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
        { userId: 2, nickname: "수연", role: "MEMBER", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1002,
      title: "JS Lv1~2 코테 대비",
      description: "프로그래머스 기출 풀이",
      maxParticipants: 8,
      currentParticipants: 8,
      status: "WAITING",
      allowCamera: false,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "suyeon",
      createdAt: now.toISOString(),
      members: [
        { userId: 3, nickname: "민지", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1003,
      title: "UI/UX 모션 야간반",
      description: "GSAP 입문부터 실습까지",
      maxParticipants: 5,
      currentParticipants: 2,
      status: "WAITING",
      allowCamera: true,
      allowAudio: false,
      allowScreenShare: false,
      createdBy: "minji",
      createdAt: now.toISOString(),
      members: [
        { userId: 4, nickname: "minji", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1004,
      title: "정처기 필기 대비반",
      description: "모의고사 풀이 스터디",
      maxParticipants: 10,
      currentParticipants: 4,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "team-catfe",
      createdAt: now.toISOString(),
      members: [
        { userId: 5, nickname: "catfe-host", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1005,
      title: "React 상태관리",
      description: "Zustand 스터디",
      maxParticipants: 7,
      currentParticipants: 5,
      status: "WAITING",
      allowCamera: true,
      allowAudio: false,
      allowScreenShare: false,
      createdBy: "uha",
      createdAt: now.toISOString(),
      members: [
        { userId: 6, nickname: "uha", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1006,
      title: "SQL 기초반",
      description: "SELECT ~ JOIN까지",
      maxParticipants: 6,
      currentParticipants: 2,
      status: "WAITING",
      allowCamera: false,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "db-kitty",
      createdAt: now.toISOString(),
      members: [
        { userId: 7, nickname: "db-kitty", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1007,
      title: "네트워크 기초",
      description: "OSI 7계층 복습",
      maxParticipants: 5,
      currentParticipants: 1,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: false,
      createdBy: "cs-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 8, nickname: "cs-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1008,
      title: "HTML/CSS 레이아웃",
      description: "반응형 실습",
      maxParticipants: 8,
      currentParticipants: 6,
      status: "WAITING",
      allowCamera: false,
      allowAudio: true,
      allowScreenShare: false,
      createdBy: "frontend-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 9, nickname: "frontend-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1009,
      title: "타입 지옥 탈출",
      description: "TS 개념 정리 (사용 안함주의)",
      maxParticipants: 4,
      currentParticipants: 2,
      status: "WAITING",
      allowCamera: true,
      allowAudio: false,
      allowScreenShare: false,
      createdBy: "no-ts-plz",
      createdAt: now.toISOString(),
      members: [
        { userId: 10, nickname: "no-ts-plz", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1010,
      title: "운영체제 스터디",
      description: "프로세스/스레드 개념",
      maxParticipants: 6,
      currentParticipants: 3,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "os-kitty",
      createdAt: now.toISOString(),
      members: [
        { userId: 11, nickname: "os-kitty", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1011,
      title: "컴퓨터 구조",
      description: "명령어 사이클, 캐시 메모리",
      maxParticipants: 6,
      currentParticipants: 3,
      status: "WAITING",
      allowCamera: true,
      allowAudio: false,
      allowScreenShare: true,
      createdBy: "arch-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 12, nickname: "arch-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },

  // 추가 12 ~ 20
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1012,
      title: "자료구조 심화",
      description: "그래프/트리 연습",
      maxParticipants: 6,
      currentParticipants: 4,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "uha",
      createdAt: now.toISOString(),
      members: [
        { userId: 13, nickname: "uha", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1013,
      title: "Docker 실습",
      description: "컨테이너 맛보기",
      maxParticipants: 8,
      currentParticipants: 2,
      status: "WAITING",
      allowCamera: false,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "dev-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 14, nickname: "dev-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1014,
      title: "리눅스 명령어",
      description: "쉘 실습",
      maxParticipants: 5,
      currentParticipants: 1,
      status: "WAITING",
      allowCamera: true,
      allowAudio: false,
      allowScreenShare: false,
      createdBy: "linux-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 15, nickname: "linux-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1015,
      title: "Git/GitHub 스터디",
      description: "브랜치 전략 연습",
      maxParticipants: 10,
      currentParticipants: 7,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: false,
      createdBy: "git-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 16, nickname: "git-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1016,
      title: "알고리즘 마라톤",
      description: "주말 집중 풀세션",
      maxParticipants: 12,
      currentParticipants: 10,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "algo-runner",
      createdAt: now.toISOString(),
      members: [
        { userId: 17, nickname: "algo-runner", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1017,
      title: "웹 보안 기초",
      description: "XSS, CSRF 실습",
      maxParticipants: 6,
      currentParticipants: 2,
      status: "WAITING",
      allowCamera: false,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "security-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 18, nickname: "security-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1018,
      title: "클린 코드 스터디",
      description: "리팩토링 사례 연구",
      maxParticipants: 8,
      currentParticipants: 5,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: false,
      createdBy: "clean-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 19, nickname: "clean-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1019,
      title: "Next.js 프로젝트",
      description: "App Router 집중",
      maxParticipants: 9,
      currentParticipants: 6,
      status: "WAITING",
      allowCamera: true,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "next-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 20, nickname: "next-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: false,
    },
  },
  {
    code: "OK",
    message: "mock success",
    success: true,
    data: {
      roomId: 1020,
      title: "AI/ML 입문",
      description: "파이썬으로 머신러닝",
      maxParticipants: 12,
      currentParticipants: 8,
      status: "WAITING",
      allowCamera: false,
      allowAudio: true,
      allowScreenShare: true,
      createdBy: "ml-cat",
      createdAt: now.toISOString(),
      members: [
        { userId: 21, nickname: "ml-cat", role: "HOST", joinedAt: now.toISOString(), lastActiveAt: now.toISOString(), online: true },
      ],
      private: true,
    },
  },
];
